#/bin/sh
# python GraphEnc/setup.py build_ext --inplace 2> /dev/null
python main.py --modeltype BC_LOSS \
                --pretrained_graph \
                --ckpt_dir weights/d2-fold/Round2/BC_LOSS-LGN \
                --ckpt n_layers=2tau1=0.07tau2=0.1w=0.5 \
                --cuda -1 \
                --root datasets/d2-fold \
                --dataset Round2 \
                --sim_mode user_embedding \
                --epoch_max 5 \
                --episode_max 64\
                --step_max 8 \
                --memory 16384 \
                --nov_beta 0.0 \
                --agent_batch 1024 \
                --dqn_mode ddqn \
                --eta 1.0 \
                --agent_lr 1e-3 \
                --replace_freq -2 \
                --num_hidden 256 \
                --tau 8e-4 \
                --gamma 0.999 \
                --cql_mode cql_H \
                --cql_alpha 5. \
                --user_lam 0.75 \
                --dueling_dqn \
                --n_augment 3 \
                --n_aug_scale 5 \
                --rare_thresh 0.1 \
                --seq_ratio 0.3 \
                --rare_ratio 0.2 \
                --rand_ratio 0.5 \
                --topk 10 \
                --eval_freq 50 \
                --episode_batch 64 \
                --all_episodes \
                --eval_query \