#/bin/sh
# python GraphEnc/setup.py build_ext --inplace 2> /dev/null
python main.py --modeltype BC_LOSS \
                --epoch 410 \
                --pretrained_graph \
                --enc_batch_size 1024 \
                --root datasets \
                --dataset d1 \
                --n_layers 2 \
                --neg_sample 128 \
                --sim_mode user_embedding \
                --freeze_epoch 5 \
                --cuda -1 \
                --episode_max 128\
                --step_max 2048 \
                --memory 16394 \
                --nov_beta 0.0 \
                --agent_batch 128 \
                --dqn_mode ddqn \
                --eta 1.0 \
                --agent_lr 5e-5 \
                --replace_freq 100 \
                --tau 0.01 \
                --gamma 0.99 \
                --cql_mode cql_H \
                --dueling_dqn \
                --n_augment 20 \
                --rare_thresh 0.1 \
                --seq_ratio 0.2 \
                --rare_ratio 0.3 \
                --rand_ratio 0.5 \
                --topk 10 \
                --eval_freq 1 \
                --policy stochastic