#/bin/sh
# python GraphEnc/setup.py build_ext --inplace 2> /dev/null
python main.py --modeltype BC_LOSS \
                --epoch 200 \
                --enc_batch_size 512 \
                --root datasets \
                --dataset d1 \
                --n_layers 2 \
                --neg_sample 128 \
                --enc_lr 1e-5 \
                --sim_mode user_embedding \
                --freeze_epoch 5 \
                --cuda -1 \
                --episode_max 512\
                --step_max 2048 \
                --memory 16394 \
                --nov_beta 0.0 \
                --agent_batch 1024 \
                --dqn_mode ddqn \
                --eta 1.0 \
                --agent_lr 5e-5 \
                --replace_freq 200 \
                --tau 0.01 \
                --gamma 0.999 \
                --cql_mode cql_H \
                --dueling_dqn \
                --n_augment 20 \
                --rare_thresh 0.1 \
                --seq_ratio 0.1 \
                --rare_ratio 0.4 \
                --rand_ratio 0.5 \